import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
// import { Roboto } from '@next/font/google'



// const roboto = Roboto({
//   subsets:['latin'],
//   weight: ['400', '700']
// })



// const cabin = localFont({
//   src: "./fonts/Poppins-Regular.ttf",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });

const cabin = localFont({
  src: "./fonts/Cabin.ttf",
  variable: "--font-geist-sans",
  weight: "100 900",
});
// const geistMono = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cabin.className}
      >
        <div className="w-full flex justify-center">{children}</div>
      </body>
    </html>
  );
}


// <html lang="en">
//   <body className={`${cabin.variable} ${geistMono.variable} antialiased`}>
//     <div className="w-full flex justify-center">{children}</div>
//   </body>
// </html>;