export default [
  {
    id: 1,
    img: "/TAĞIYEV-NEFT.jpg",
    category: `Təqdimat`,
    title: "“TAĞIYEV: NEFT” FİLMİNİN TƏQDİMATI KEÇİRİLİB",
    date: "Noyabr 11, 2024",
    author: "Nattasha",
  },
  {
    id: 2,
    img: "/2.jpeg",
    category: "Təqdimat",
    title: "“KÖHNƏ ÇAMADANLAR” FİLMİ TÜRKİYƏDƏ NÜMAYİŞ OLUNUB",
    date: "Noyabr 8, 2024",
    author: "Nattasha",
  },
  {
    id: 3,
    img: "/3.jpg",
    category: "Film",
    title: "“HOZU 007” KİNOTEATRLARDA",
    date: "Noyabr 3, 2024",
    author: "Nattasha",
  },
  {
    id: 4,
    img: "/4.jpg",
    category: "Film",
    title: "ƏLİXAN RƏCƏBOVUN “SƏRİYYƏ” FİLMİ TEZLİKLƏ KİNOTEATRLARDA",
    date: "Oktyabr 18, 2024",
    author: "Nattasha",
  },
  {
    id: 5,
    img: "./blog/cards/5.jpg",
    category: "Development",
    title: "Turn Emails & Attachments Into To-Dos with Apps",
    date: "May 02, 2022",
    author: "Nattasha",
  },
  {
    id: 6,
    img: "./blog/cards/cardSmall1.jpg",
    category: "Business",
    title: "Turn Emails & Attachments Into To-Dos with Apps",
    date: "May 02, 2022",
    author: "Peter",
  },
  {
    id: 7,
    img: "./blog/cards/cardSmall2.jpg",
    category: "Marketing",
    title: "Turn Emails & Attachments Into To-Dos with Apps",
    date: "May 02, 2022",
    author: "Nattasha",
  },
  {
    id: 8,
    img: "./blog/cards/cardSmall3.jpg",
    category: "Creative",
    title: "Turn Emails & Attachments Into To-Dos with Apps",
    date: "May 02, 2022",
    author: "Robert	Oliver",
  },
];